### ISSUE TITLE
assertNotEqual(obj, nullptr) fails on a real board

### ISSUE THREAD

**Issue by reymalahay** [bxparks/AUnit#118]
hi there,

hi there,

**Is your feature request related to a problem? Please describe.**
i have a test that `asserts` the validity of a newly instantiated object. more specifically, when i run the following test
```
test(object_valid) {

    MyClass *obj;
    
    assertNotEqual(obj, nullptr);
}
```

the expected result should be `obj` and `nullptr` are not equal. this test passes when it is executed in `EpoxyDuino`. but it fails on a real board. 

**Describe the solution you'd like**
`assertNotEqual(obj, nullptr)` must pass when a class is instantiated successfully.

**Describe alternatives you've considered**
n/a. 

**Additional context**
board: Arduino Uno
environment: Linux
compiler: /usr/bin/g++

sample test:
```
test(object_valid) {

    MyClass *obj;
    
    assertNotEqual(obj, nullptr);
}
```

Makefile:
```
APP_NAME := lab1_code_test
ARDUINO_LIBS := AUnit
include ${EPOXY_HOME}/EpoxyDuino.mk
```

commands:
```
make clean

make

make run
```

please advise.

thanks in advance,
rey malahay

**Comment by bxparks** [comment]
I will answer your question by asking you a question: Why do you think the `obj` pointer is null? If you don't know the answer, you probably need to refresh your knowledge of C and C++. If you simply forgot how the C/C++ language works, that's fair, it can happen.

Now my bigger concern is that you are flooding me with Issues and Discussions: 14 tickets in 3 weeks. Even just reading them takes time and energy, to figure out whether it is a valid Issue, or whether it belongs in a Discussion. Some of your posts have been duplicates. Some have been filed in the wrong project. I just don't have the time and energy for your tickets. So I am going to close all of them, because I won't be able to get to them.
